# Generated by Django 4.2.6 on 2023-10-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_quizcategory_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='level',
        ),
    ]
