# Generated by Django 4.2.6 on 2023-10-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_quizquestion_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
    ]
